### ISSUE TITLE
When no upcoming trip data is available next destination displays an invalid value

### ISSUE THREAD

**Issue by ManuelBauer** [KrauseFx/whereisfelix.today-backend#41]
When no upcoming trip data is available, the next destination displays invalid data 😉
Or do you try to build a time machine ⏰🤪 ("Leaving for 49 years ago")

Happy holiday 🏖

<img width="601" alt="Screenshot 2019-03-09 at 11 08 52" src="https://user-images.githubusercontent.com/1709215/54069949-c2d97880-425b-11e9-8082-671165954f64.png">

**Comment by KrauseFx** [comment]
Oh noooo 😢

**Comment by KrauseFx** [comment]
Thanks for letting me know, need to fix it

**Comment by KrauseFx** [comment]
Temporarlily fixed by adding another trip

**Comment by KrauseFx** [comment]
This has been fixed, thank you
