### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by skywinder** [KrauseFx/whereisfelix.today-backend#71]
did you invent the time machine? :)
<img width="470" alt="image" src="https://user-images.githubusercontent.com/3356474/69618542-a50fa600-106c-11ea-99bc-48199d6ee270.png">

**Comment by KrauseFx** [comment]
Haha, yah something's off

**Comment by KrauseFx** [comment]
won't fix myself though, too much work with time zones and times and such haha
